/*
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class AmfOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
