/*
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.tests

import com.google.inject.Inject
import de.luh.se.mbse.network.textualeditor.amf.Network
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(AmfInjectorProvider)
class AmfParsingTest{

	@Inject
	ParseHelper<Network> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
