/*
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.ui.tests;

import com.google.inject.Injector;
import de.luh.se.mbse.network.textualeditor.ui.internal.TextualeditorActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class AmfUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TextualeditorActivator.getInstance().getInjector("de.luh.se.mbse.network.textualeditor.Amf");
	}

}
