/*
 * generated by Xtext 2.9.2
 */
package de.luh.se.mbse.statemachine.textualeditor.ui;

import com.google.inject.Injector;
import de.luh.se.mbse.statemachine.textualeditor.ui.internal.TextualeditorActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AMFExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TextualeditorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TextualeditorActivator.getInstance().getInjector(TextualeditorActivator.DE_LUH_SE_MBSE_STATEMACHINE_TEXTUALEDITOR_AMF);
	}
	
}
