/*
 * generated by Xtext 2.9.2
 */
package de.luh.se.mbse.statemachine.textualeditor


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AMFRuntimeModule extends AbstractAMFRuntimeModule {
}
