/*
 * generated by Xtext 2.9.2
 */
package de.luh.se.mbse.statemachine.textualeditor


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AMFStandaloneSetup extends AMFStandaloneSetupGenerated {

	def static void doSetup() {
		new AMFStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
