/*
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAmfScopeProvider extends DelegatingScopeProvider {
}
