/**
 * generated by Xtext 2.9.2
 */
package de.luh.se.mbse.statemachine.textualeditor;

import de.luh.se.mbse.statemachine.textualeditor.AbstractAMFRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AMFRuntimeModule extends AbstractAMFRuntimeModule {
}
