/**
 * generated by Xtext 2.9.2
 */
package de.luh.se.mbse.statemachine.textualeditor;

import de.luh.se.mbse.statemachine.textualeditor.AMFStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AMFStandaloneSetup extends AMFStandaloneSetupGenerated {
  public static void doSetup() {
    AMFStandaloneSetup _aMFStandaloneSetup = new AMFStandaloneSetup();
    _aMFStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
