/**
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.ui;

import de.luh.se.mbse.network.textualeditor.ui.AbstractAmfUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AmfUiModule extends AbstractAmfUiModule {
  public AmfUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
