/**
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.amf;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.luh.se.mbse.network.textualeditor.amf.AmfFactory
 * @model kind="package"
 * @generated
 */
public interface AmfPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "amf";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "de.luh.se.mbse.network.textualeditor.Amf";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "amf";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AmfPackage eINSTANCE = de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl.init();

  /**
   * The meta object id for the '{@link de.luh.se.mbse.network.textualeditor.amf.impl.NetworkImpl <em>Network</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.NetworkImpl
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getNetwork()
   * @generated
   */
  int NETWORK = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETWORK__NAME = 0;

  /**
   * The feature id for the '<em><b>Channel</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETWORK__CHANNEL = 1;

  /**
   * The feature id for the '<em><b>Statemachine</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETWORK__STATEMACHINE = 2;

  /**
   * The number of structural features of the '<em>Network</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETWORK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.luh.se.mbse.network.textualeditor.amf.impl.StatemachineImpl <em>Statemachine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.StatemachineImpl
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getStatemachine()
   * @generated
   */
  int STATEMACHINE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMACHINE__NAME = 0;

  /**
   * The feature id for the '<em><b>Initialstate</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMACHINE__INITIALSTATE = 1;

  /**
   * The feature id for the '<em><b>State</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMACHINE__STATE = 2;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMACHINE__TRANSITION = 3;

  /**
   * The number of structural features of the '<em>Statemachine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMACHINE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link de.luh.se.mbse.network.textualeditor.amf.impl.ChannelImpl <em>Channel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.ChannelImpl
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getChannel()
   * @generated
   */
  int CHANNEL = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHANNEL__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHANNEL__NAME = 1;

  /**
   * The number of structural features of the '<em>Channel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHANNEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.luh.se.mbse.network.textualeditor.amf.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.TransitionImpl
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 3;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__SOURCE = 0;

  /**
   * The feature id for the '<em><b>Channel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__CHANNEL = 1;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TARGET = 2;

  /**
   * The feature id for the '<em><b>Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__EVENT = 3;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link de.luh.se.mbse.network.textualeditor.amf.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.StateImpl
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getState()
   * @generated
   */
  int STATE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 0;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.luh.se.mbse.network.textualeditor.amf.TypeOfChannel <em>Type Of Channel</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.luh.se.mbse.network.textualeditor.amf.TypeOfChannel
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getTypeOfChannel()
   * @generated
   */
  int TYPE_OF_CHANNEL = 5;

  /**
   * The meta object id for the '{@link de.luh.se.mbse.network.textualeditor.amf.Event <em>Event</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.luh.se.mbse.network.textualeditor.amf.Event
   * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 6;


  /**
   * Returns the meta object for class '{@link de.luh.se.mbse.network.textualeditor.amf.Network <em>Network</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Network</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Network
   * @generated
   */
  EClass getNetwork();

  /**
   * Returns the meta object for the attribute '{@link de.luh.se.mbse.network.textualeditor.amf.Network#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Network#getName()
   * @see #getNetwork()
   * @generated
   */
  EAttribute getNetwork_Name();

  /**
   * Returns the meta object for the containment reference list '{@link de.luh.se.mbse.network.textualeditor.amf.Network#getChannel <em>Channel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Channel</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Network#getChannel()
   * @see #getNetwork()
   * @generated
   */
  EReference getNetwork_Channel();

  /**
   * Returns the meta object for the containment reference list '{@link de.luh.se.mbse.network.textualeditor.amf.Network#getStatemachine <em>Statemachine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statemachine</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Network#getStatemachine()
   * @see #getNetwork()
   * @generated
   */
  EReference getNetwork_Statemachine();

  /**
   * Returns the meta object for class '{@link de.luh.se.mbse.network.textualeditor.amf.Statemachine <em>Statemachine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statemachine</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Statemachine
   * @generated
   */
  EClass getStatemachine();

  /**
   * Returns the meta object for the attribute '{@link de.luh.se.mbse.network.textualeditor.amf.Statemachine#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Statemachine#getName()
   * @see #getStatemachine()
   * @generated
   */
  EAttribute getStatemachine_Name();

  /**
   * Returns the meta object for the reference '{@link de.luh.se.mbse.network.textualeditor.amf.Statemachine#getInitialstate <em>Initialstate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Initialstate</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Statemachine#getInitialstate()
   * @see #getStatemachine()
   * @generated
   */
  EReference getStatemachine_Initialstate();

  /**
   * Returns the meta object for the containment reference list '{@link de.luh.se.mbse.network.textualeditor.amf.Statemachine#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>State</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Statemachine#getState()
   * @see #getStatemachine()
   * @generated
   */
  EReference getStatemachine_State();

  /**
   * Returns the meta object for the containment reference list '{@link de.luh.se.mbse.network.textualeditor.amf.Statemachine#getTransition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transition</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Statemachine#getTransition()
   * @see #getStatemachine()
   * @generated
   */
  EReference getStatemachine_Transition();

  /**
   * Returns the meta object for class '{@link de.luh.se.mbse.network.textualeditor.amf.Channel <em>Channel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Channel</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Channel
   * @generated
   */
  EClass getChannel();

  /**
   * Returns the meta object for the attribute list '{@link de.luh.se.mbse.network.textualeditor.amf.Channel#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Type</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Channel#getType()
   * @see #getChannel()
   * @generated
   */
  EAttribute getChannel_Type();

  /**
   * Returns the meta object for the attribute '{@link de.luh.se.mbse.network.textualeditor.amf.Channel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Channel#getName()
   * @see #getChannel()
   * @generated
   */
  EAttribute getChannel_Name();

  /**
   * Returns the meta object for class '{@link de.luh.se.mbse.network.textualeditor.amf.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the reference '{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Transition#getSource()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Source();

  /**
   * Returns the meta object for the reference '{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getChannel <em>Channel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Channel</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Transition#getChannel()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Channel();

  /**
   * Returns the meta object for the reference '{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Transition#getTarget()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Target();

  /**
   * Returns the meta object for the attribute '{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Event</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Transition#getEvent()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Event();

  /**
   * Returns the meta object for class '{@link de.luh.se.mbse.network.textualeditor.amf.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link de.luh.se.mbse.network.textualeditor.amf.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for enum '{@link de.luh.se.mbse.network.textualeditor.amf.TypeOfChannel <em>Type Of Channel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Type Of Channel</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.TypeOfChannel
   * @generated
   */
  EEnum getTypeOfChannel();

  /**
   * Returns the meta object for enum '{@link de.luh.se.mbse.network.textualeditor.amf.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Event</em>'.
   * @see de.luh.se.mbse.network.textualeditor.amf.Event
   * @generated
   */
  EEnum getEvent();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AmfFactory getAmfFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.luh.se.mbse.network.textualeditor.amf.impl.NetworkImpl <em>Network</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.NetworkImpl
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getNetwork()
     * @generated
     */
    EClass NETWORK = eINSTANCE.getNetwork();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NETWORK__NAME = eINSTANCE.getNetwork_Name();

    /**
     * The meta object literal for the '<em><b>Channel</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NETWORK__CHANNEL = eINSTANCE.getNetwork_Channel();

    /**
     * The meta object literal for the '<em><b>Statemachine</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NETWORK__STATEMACHINE = eINSTANCE.getNetwork_Statemachine();

    /**
     * The meta object literal for the '{@link de.luh.se.mbse.network.textualeditor.amf.impl.StatemachineImpl <em>Statemachine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.StatemachineImpl
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getStatemachine()
     * @generated
     */
    EClass STATEMACHINE = eINSTANCE.getStatemachine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMACHINE__NAME = eINSTANCE.getStatemachine_Name();

    /**
     * The meta object literal for the '<em><b>Initialstate</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMACHINE__INITIALSTATE = eINSTANCE.getStatemachine_Initialstate();

    /**
     * The meta object literal for the '<em><b>State</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMACHINE__STATE = eINSTANCE.getStatemachine_State();

    /**
     * The meta object literal for the '<em><b>Transition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMACHINE__TRANSITION = eINSTANCE.getStatemachine_Transition();

    /**
     * The meta object literal for the '{@link de.luh.se.mbse.network.textualeditor.amf.impl.ChannelImpl <em>Channel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.ChannelImpl
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getChannel()
     * @generated
     */
    EClass CHANNEL = eINSTANCE.getChannel();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHANNEL__TYPE = eINSTANCE.getChannel_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHANNEL__NAME = eINSTANCE.getChannel_Name();

    /**
     * The meta object literal for the '{@link de.luh.se.mbse.network.textualeditor.amf.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.TransitionImpl
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__SOURCE = eINSTANCE.getTransition_Source();

    /**
     * The meta object literal for the '<em><b>Channel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__CHANNEL = eINSTANCE.getTransition_Channel();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TARGET = eINSTANCE.getTransition_Target();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__EVENT = eINSTANCE.getTransition_Event();

    /**
     * The meta object literal for the '{@link de.luh.se.mbse.network.textualeditor.amf.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.StateImpl
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '{@link de.luh.se.mbse.network.textualeditor.amf.TypeOfChannel <em>Type Of Channel</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.luh.se.mbse.network.textualeditor.amf.TypeOfChannel
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getTypeOfChannel()
     * @generated
     */
    EEnum TYPE_OF_CHANNEL = eINSTANCE.getTypeOfChannel();

    /**
     * The meta object literal for the '{@link de.luh.se.mbse.network.textualeditor.amf.Event <em>Event</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.luh.se.mbse.network.textualeditor.amf.Event
     * @see de.luh.se.mbse.network.textualeditor.amf.impl.AmfPackageImpl#getEvent()
     * @generated
     */
    EEnum EVENT = eINSTANCE.getEvent();

  }

} //AmfPackage
