/**
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.amf;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Network</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.luh.se.mbse.network.textualeditor.amf.Network#getName <em>Name</em>}</li>
 *   <li>{@link de.luh.se.mbse.network.textualeditor.amf.Network#getChannel <em>Channel</em>}</li>
 *   <li>{@link de.luh.se.mbse.network.textualeditor.amf.Network#getStatemachine <em>Statemachine</em>}</li>
 * </ul>
 *
 * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getNetwork()
 * @model
 * @generated
 */
public interface Network extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getNetwork_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.luh.se.mbse.network.textualeditor.amf.Network#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Channel</b></em>' containment reference list.
   * The list contents are of type {@link de.luh.se.mbse.network.textualeditor.amf.Channel}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channel</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channel</em>' containment reference list.
   * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getNetwork_Channel()
   * @model containment="true"
   * @generated
   */
  EList<Channel> getChannel();

  /**
   * Returns the value of the '<em><b>Statemachine</b></em>' containment reference list.
   * The list contents are of type {@link de.luh.se.mbse.network.textualeditor.amf.Statemachine}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Statemachine</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statemachine</em>' containment reference list.
   * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getNetwork_Statemachine()
   * @model containment="true"
   * @generated
   */
  EList<Statemachine> getStatemachine();

} // Network
