/**
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.amf;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statemachine</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.luh.se.mbse.network.textualeditor.amf.Statemachine#getName <em>Name</em>}</li>
 *   <li>{@link de.luh.se.mbse.network.textualeditor.amf.Statemachine#getInitialstate <em>Initialstate</em>}</li>
 *   <li>{@link de.luh.se.mbse.network.textualeditor.amf.Statemachine#getState <em>State</em>}</li>
 *   <li>{@link de.luh.se.mbse.network.textualeditor.amf.Statemachine#getTransition <em>Transition</em>}</li>
 * </ul>
 *
 * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getStatemachine()
 * @model
 * @generated
 */
public interface Statemachine extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getStatemachine_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.luh.se.mbse.network.textualeditor.amf.Statemachine#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Initialstate</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Initialstate</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initialstate</em>' reference.
   * @see #setInitialstate(State)
   * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getStatemachine_Initialstate()
   * @model
   * @generated
   */
  State getInitialstate();

  /**
   * Sets the value of the '{@link de.luh.se.mbse.network.textualeditor.amf.Statemachine#getInitialstate <em>Initialstate</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initialstate</em>' reference.
   * @see #getInitialstate()
   * @generated
   */
  void setInitialstate(State value);

  /**
   * Returns the value of the '<em><b>State</b></em>' containment reference list.
   * The list contents are of type {@link de.luh.se.mbse.network.textualeditor.amf.State}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>State</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' containment reference list.
   * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getStatemachine_State()
   * @model containment="true"
   * @generated
   */
  EList<State> getState();

  /**
   * Returns the value of the '<em><b>Transition</b></em>' containment reference list.
   * The list contents are of type {@link de.luh.se.mbse.network.textualeditor.amf.Transition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Transition</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transition</em>' containment reference list.
   * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getStatemachine_Transition()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransition();

} // Statemachine
