/**
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.amf;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getSource <em>Source</em>}</li>
 *   <li>{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getChannel <em>Channel</em>}</li>
 *   <li>{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getTarget <em>Target</em>}</li>
 *   <li>{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getEvent <em>Event</em>}</li>
 * </ul>
 *
 * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getTransition()
 * @model
 * @generated
 */
public interface Transition extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(State)
   * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getTransition_Source()
   * @model
   * @generated
   */
  State getSource();

  /**
   * Sets the value of the '{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(State value);

  /**
   * Returns the value of the '<em><b>Channel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channel</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channel</em>' reference.
   * @see #setChannel(Channel)
   * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getTransition_Channel()
   * @model
   * @generated
   */
  Channel getChannel();

  /**
   * Sets the value of the '{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getChannel <em>Channel</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Channel</em>' reference.
   * @see #getChannel()
   * @generated
   */
  void setChannel(Channel value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(State)
   * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getTransition_Target()
   * @model
   * @generated
   */
  State getTarget();

  /**
   * Sets the value of the '{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(State value);

  /**
   * Returns the value of the '<em><b>Event</b></em>' attribute.
   * The literals are from the enumeration {@link de.luh.se.mbse.network.textualeditor.amf.Event}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Event</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' attribute.
   * @see de.luh.se.mbse.network.textualeditor.amf.Event
   * @see #setEvent(Event)
   * @see de.luh.se.mbse.network.textualeditor.amf.AmfPackage#getTransition_Event()
   * @model
   * @generated
   */
  Event getEvent();

  /**
   * Sets the value of the '{@link de.luh.se.mbse.network.textualeditor.amf.Transition#getEvent <em>Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' attribute.
   * @see de.luh.se.mbse.network.textualeditor.amf.Event
   * @see #getEvent()
   * @generated
   */
  void setEvent(Event value);

} // Transition
