/**
 * generated by Xtext 2.9.2
 */
package de.luh.se.mbse.statemachine.textualeditor.amfRules;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Channel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.luh.se.mbse.statemachine.textualeditor.amfRules.Channel#getType <em>Type</em>}</li>
 *   <li>{@link de.luh.se.mbse.statemachine.textualeditor.amfRules.Channel#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see de.luh.se.mbse.statemachine.textualeditor.amfRules.AmfRulesPackage#getChannel()
 * @model
 * @generated
 */
public interface Channel extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute list.
   * The list contents are of type {@link de.luh.se.mbse.statemachine.textualeditor.amfRules.TypeOfChannel}.
   * The literals are from the enumeration {@link de.luh.se.mbse.statemachine.textualeditor.amfRules.TypeOfChannel}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute list.
   * @see de.luh.se.mbse.statemachine.textualeditor.amfRules.TypeOfChannel
   * @see de.luh.se.mbse.statemachine.textualeditor.amfRules.AmfRulesPackage#getChannel_Type()
   * @model unique="false"
   * @generated
   */
  EList<TypeOfChannel> getType();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.luh.se.mbse.statemachine.textualeditor.amfRules.AmfRulesPackage#getChannel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.luh.se.mbse.statemachine.textualeditor.amfRules.Channel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Channel
