/**
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.validation;

import de.luh.se.mbse.network.textualeditor.validation.AbstractAmfValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AmfValidator extends AbstractAmfValidator {
}
