/*
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AmfAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/luh/se/mbse/network/textualeditor/parser/antlr/internal/InternalAmf.tokens");
	}
}
