/*
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor.parser.antlr;

import com.google.inject.Inject;
import de.luh.se.mbse.network.textualeditor.parser.antlr.internal.InternalAmfParser;
import de.luh.se.mbse.network.textualeditor.services.AmfGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AmfParser extends AbstractAntlrParser {

	@Inject
	private AmfGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAmfParser createParser(XtextTokenStream stream) {
		return new InternalAmfParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Network";
	}

	public AmfGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AmfGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
