/**
 * generated by Xtext 2.9.2
 */
package de.luh.se.mbse.statemachine.textualeditor.ui.contentassist;

import de.luh.se.mbse.statemachine.textualeditor.ui.contentassist.AbstractAMFProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AMFProposalProvider extends AbstractAMFProposalProvider {
}
