/*
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AmfRuntimeModule extends AbstractAmfRuntimeModule {
}
