/*
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AmfStandaloneSetup extends AmfStandaloneSetupGenerated {

	def static void doSetup() {
		new AmfStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
