/*
 * generated by Xtext 2.9.2
 */
package de.luh.se.mbse.statemachine.textualeditor.ui.tests;

import com.google.inject.Injector;
import de.luh.se.mbse.statemachine.textualeditor.ui.internal.TextualeditorActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class AMFUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TextualeditorActivator.getInstance().getInjector("de.luh.se.mbse.statemachine.textualeditor.AMF");
	}

}
