/**
 * generated by Xtext 2.9.1
 */
package de.luh.se.mbse.network.textualeditor;

import de.luh.se.mbse.network.textualeditor.AmfStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AmfStandaloneSetup extends AmfStandaloneSetupGenerated {
  public static void doSetup() {
    AmfStandaloneSetup _amfStandaloneSetup = new AmfStandaloneSetup();
    _amfStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
